export let products = [
  {
    id: 1,
    title: "Salchipapa",
    price: "15000",
    stock: 20,
    description:
      "Salchipapa con salchicha, papa, pollo, guacamole, pico de gallo y salsa de la casa",
    category: "comida",
    img: "https://res.cloudinary.com/dtfwp778q/image/upload/f_auto,q_auto/nm4607xxr3j0yh6jlglp",
  },
  {
    id: 2,
    title: "Arepas",
    price: "10000",
    stock: 20,
    description:
      "Arepas pollo o carne, guacamole, pico de gallo y salsa de la casa",
    category: "comida",
    img: "https://res.cloudinary.com/dtfwp778q/image/upload/f_auto,q_auto/exl5dxufqcm8r6hmxakb",
  },
  {
    id: 3,
    title: "Alitas Bbq",
    price: "20000",
    stock: 20,
    description: "Alitas bbq",
    category: "comida",
    img: "https://res.cloudinary.com/dtfwp778q/image/upload/f_auto,q_auto/dsqd7o4k8lwmquhhbnpa",
  },
  {
    id: 4,
    title: "Mojito",
    price: "8000",
    stock: 100,
    description: "Mojito",
    category: "cocteles",
    img: "https://res.cloudinary.com/dtfwp778q/image/upload/f_auto,q_auto/spsxexfef3cpzn5mhe1c",
  },
  {
    id: 4,
    title: "Margarita",
    price: "8000",
    stock: 100,
    description: "Margarita",
    category: "cocteles",
    img: "https://res.cloudinary.com/dtfwp778q/image/upload/f_auto,q_auto/cepo4lsnoqjjua4ltend",
  },
  {
    id: 5,
    title: "Tequila Jimador",
    price: "8000",
    stock: 10,
    description: "Tequila Jimador",
    category: "tragos",
    img: "https://res.cloudinary.com/dtfwp778q/image/upload/f_auto,q_auto/a2nhbytgk2djxh4j5spu",
  },
];
